targets:
  $default:
    builders:
      drift_dev|drift_dev:
        generate_for:
          - lib/foundation/offline/offline_database.dart
      json_serializable|json_serializable:
        generate_for:
          - lib/models/*.dart
          - lib/models/dtos/*.dart
      freezed|freezed:
        generate_for:
          - lib/models/*.dart
          - lib/models/dtos/*.dart
